# Generated by Django 4.2.8 on 2023-12-28 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='category',
            new_name='Category',
        ),
    ]
