# Generated by Django 4.2.8 on 2024-01-01 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_expense_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.users'),
        ),
    ]
