# Generated by Django 4.2.8 on 2024-01-01 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_expense_username_alter_expense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='username',
        ),
    ]
