# Generated by Django 4.2.8 on 2024-01-01 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_remove_expense_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='user',
            new_name='userr',
        ),
    ]
