# Generated by Django 4.2.8 on 2024-01-01 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_rename_user_expense_userr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='userr',
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.users'),
        ),
    ]
